# Single dimentional NumPY Array

In [2]:
import numpy as np
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [4]:
import numpy as np

In [6]:
n1=np.array([10,20,30,40])

In [8]:
n1

array([10, 20, 30, 40])

In [10]:
n1[1]

20

In [11]:
n1[0:3]

array([10, 20, 30])

In [12]:
n1[-1]

40

In [13]:
n1[-1:-3]

array([], dtype=int32)

In [14]:
n1[-1:3]

array([], dtype=int32)

In [15]:
nn1[2:-1]

NameError: name 'nn1' is not defined

In [16]:
n1[2:-1]

array([30])

In [17]:
type(n1)

numpy.ndarray

# Multidimentional MumPy array

In [18]:
import numpy as np

In [20]:
n2=np.array([[10,20,30],[10,80,90],[30,50,80]])

In [21]:
n2

array([[10, 20, 30],
       [10, 80, 90],
       [30, 50, 80]])

# initialize NumPy array with zeros

In [22]:
n3=np.zeros((2,3))

In [23]:
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

# initialization of Numpy array with full then

In [24]:
n4=np.full((3,3),9)

In [25]:
n4

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

# initialize NumPy array within a range

In [26]:
n5=np.arange(10,20)

In [27]:
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
print(n5)

[10 11 12 13 14 15 16 17 18 19]


# initialization of the NumPy array wit the skip numbers

In [39]:
n6=np.arange(1,20,2)

In [41]:
n6

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# Initilaization of NumPy array with random numbers

In [32]:
n7=np.random.randint(100,1000,10)

In [33]:
n7

array([803, 703, 894, 639, 738, 767, 654, 104, 718, 196])

# initialization of the array shape changes in a fraction of seconds

In [34]:
    n8=np.array([[10,20,30],[10,40,30],[30,40,60],[50,70,90]])

In [35]:
n8

array([[10, 20, 30],
       [10, 40, 30],
       [30, 40, 60],
       [50, 70, 90]])

In [36]:
n8.shape

(4, 3)

In [37]:
n8.shape=(3,4)

In [38]:
n8

array([[10, 20, 30, 10],
       [40, 30, 30, 40],
       [60, 50, 70, 90]])

# 

# Joining NumPy Array

In [42]:
import numpy as np

In [43]:
a=np.array([10,20,30])
b=np.array([30,40,50])

In [44]:
np.vstack((a,b))

array([[10, 20, 30],
       [30, 40, 50]])

In [45]:
np.hstack((a,b))

array([10, 20, 30, 30, 40, 50])

In [46]:
np.column_stack((a,b))

array([[10, 30],
       [20, 40],
       [30, 50]])

In [47]:
np.array((a,b))

array([[10, 20, 30],
       [30, 40, 50]])

In [48]:
c=np.array([15,25,35])

In [50]:
np.vstack((a,b,c))

array([[10, 20, 30],
       [30, 40, 50],
       [15, 25, 35]])

In [51]:
np.column_stack((a,b,c))

array([[10, 30, 15],
       [20, 40, 25],
       [30, 50, 35]])

In [52]:
np.array((a,b,c))

array([[10, 20, 30],
       [30, 40, 50],
       [15, 25, 35]])

In [54]:
np.intersect1d(a,b)

array([30])

In [55]:
np.intersect1d(a,c)

array([], dtype=int32)

In [56]:
np.sum([a,b])

180

In [57]:
np.sum([a,b,c])

255

In [58]:
np.sum([a,b],axis=0)

array([40, 60, 80])

In [59]:
np.sum([a,b],axis=1)

array([ 60, 120])

In [60]:
np.setdiff1d(a,b)

array([10, 20])

# NumPy array Mathematics

In [61]:
p=np.array([20,40,60])

In [62]:
p+1

array([21, 41, 61])

In [63]:
p/2

array([10., 20., 30.])

In [64]:
p*3

array([ 60, 120, 180])

In [65]:
p-5

array([15, 35, 55])

In [67]:
p**2

array([ 400, 1600, 3600])

# NumPy Math function

In [69]:
import numpy as np
nn=np.array((5,10,15,20))

In [71]:
np.mean(nn)

12.5

In [72]:
np.median(nn)

12.5

In [73]:
np.std(nn)

5.5901699437494745

In [75]:
np.argmax(nn)

3

# Saving and Loading NumPy

In [76]:
import numpy as np

In [77]:
n11=np.array([10,20,30,40,50])

In [78]:
np.save('Sanjeeta',n11)

In [79]:
n11

array([10, 20, 30, 40, 50])

In [81]:
np.load('Sanjeeta.npy')

array([10, 20, 30, 40, 50])